# Using the EconomyAPI and PiggyCustomEnchants plugins if you used them put them on true instead of false !
  # EconomyAPI: https://poggit.pmmp.io/p/EconomyAPI
  # PiggyCustomEnchants: https://poggit.pmmp.io/p/PiggyCustomEnchants
usage-of-EconomyAPI: false
usage-of-PiggyCustomEnchants: false

# Item of the LuckyBlock (default 19: sponge):
  # id:meta
block: "19:0"

# Useful tips before starting the configuration:
  # You can use {playerName} tag to add the player name to a command, message...
  # Item id/meta list: https://bit.ly/2J0l7QU
  # Basic enchantment name/id list: https://bit.ly/2GJXaun
  # PiggyCustomEnchants enchantment name/id list: https://bit.ly/2GVQSYX

# Configuration of the loots (there are currently 5 different possibilities which will be described below):
loot:
  # items -> give a item to the player (that supports PiggyCustomEnchants), examples:
    # - items: ["id:meta-count", "id-count", "id"]
    # - items: ["id-count-itemName"]
    # - items: ["id-count-DEFAULT-enchantName-enchantLevel"]
  - items: []
  # blocks -> replace the LuckyBlock by another block, examples:
    # - block: "id:meta"
  - block: 57
  - block: 41
  - block: 10
  - block: 30
  # commands-player -> execute commands from the player, examples:
    # - commands-player: [me "Bluzzi is too strong..."]
    # - commands-player: ["help 1", "help 2"]
  - commands-player: ["givetoken '{playerName}' 25"]
  - commands-player: ["givetoken '{playerName}' 50"]
  - commands-player: ["givetoken '{playerName}' 75"]
  - commands-player: ["givetoken '{playerName}' 100"]
  # commands-server -> execute commands from the server, examples:
    # - commands-server: ["say {playerName} broke a LuckyBlock."]
  - commands-server: []
  # money -> give money to a player (be careful, this feature requires the activation of the EconomyAPI plugin), examples:
    # - money: count
  - money: 10000
  - money: 15000
  - money: 20000
  - money: 25000
  - money: 30000
  - money: 35000

# Plugin's version, please don't touch it !
version: "1.1"
